### ISSUE TITLE
when measues  Benmarksql 5.0， it pops out duplicate key error.

### ISSUE THREAD

**Issue by cyberspicecai** [Tencent/TBase#29]
01:15:45,792 [Thread-30] ERROR  jTPCCTData : Unexpected SQLException in NEW_ORDER
01:15:45,792 [Thread-30] ERROR  jTPCCTData : ERROR: node:dn001, backend_pid:29859, nodename:dn001,backend_pid:29859,message:duplicate key value violates unique constraint "bmsql_oorder_pkey"
  Detail: Key (o_w_id, o_d_id, o_id)=(5, 10, 3005) already exists.
org.postgresql.util.PSQLException: ERROR: node:dn001, backend_pid:29859, nodename:dn001,backend_pid:29859,message:duplicate key value violates unique constraint "bmsql_oorder_pkey"
  Detail: Key (o_w_id, o_d_id, o_id)=(5, 10, 3005) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
        at jTPCCTData.executeNewOrder(jTPCCTData.java:410)
        at jTPCCTData.execute(jTPCCTData.java:95)
        at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:261)
        at jTPCCTerminal.run(jTPCCTerminal.java:88)
        at java.lang.Thread.run(Thread.java:748)

**Comment by SuCuicui** [comment]
Is now the problem solved? 
How about deleting the data and reimporting it?

**Comment by cyberspicecai** [comment]
it isn't related to data preparing.  restoring data doesn't work.
