### ISSUE TITLE
benmarksql测试的时候遇到的错误

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#49]
SELECT max(o_id) FROM bmsql_oorder WHERE o_w_id = 4 AND o_d_id = 7 AND o_c_id = 916;
查询结果：2573
select * from bmsql_oorder where o_w_id=4 and o_d_id=7 and o_c_id=916
and o_id=(2573);
可以查询到一条记录；
select * from bmsql_oorder where o_w_id=4 and o_d_id=7 and o_c_id=916
and o_id=(
	select max(o_id) from bmsql_oorder where o_w_id=4 and o_d_id=7 and o_c_id=916
)；
无法查询到结果？
是在做benmarksql测试的时候遇到的错误：
TAL  jTPCCTerminal : Last Order for W_ID=4 D_ID=7 C_ID=916 not found963MB                                   
java.lang.Exception: Last Order for W_ID=4 D_ID=7 C_ID=916 not found
	at jTPCCTData.executeOrderStatus(jTPCCTData.java:1189)
	at jTPCCTData.execute(jTPCCTData.java:103)
	at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:204)
	at jTPCCTerminal.run(jTPCCTerminal.java:88)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JennyJennyChen** [comment]
我这边没有遇到过这个问题，能详细说一下你那边的操作步骤？是否在这个之前出现过什么其他错误而导致？

**Comment by qiukemoxi** [comment]
我也遇到过这个问题，Last Order for W_ID=4 D_ID=x C_ID=x not found，并且还有各种类型，item 9250 not found，District for W_ID=81 D_ID not foundSTOCK with S_W_ID=46155 not found等等。然后benchmarksql就调用system.Exit(4)退出了。tpcc中断了。
